customhost = "database-1.cgzss1uvc4e8.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "kungweixin-employee"
customregion = "us-east-1"
